# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txLMkyui0XRyCNs53LPEr614pJQ6T9Ey
"""

import streamlit as st
import pandas as pd
import xgboost as xgb
import plotly.express as px
from sklearn.model_selection import train_test_split
import numpy as np

# Konfigurasi Halaman
st.set_page_config(page_title="NextHit Analytics", page_icon="🎮", layout="wide")

# Header Dashboard
st.title("🎮 NextHit: Video Game Sales Analytics")
st.markdown("Prototipe Prediksi Penjualan Global Video Game Menggunakan Machine Learning (XGBoost)")
st.divider()

# Load Data dari GitHub (Lokal)
@st.cache_data
def load_data():
    return pd.read_csv('games.csv')

try:
    df_games = load_data()
except FileNotFoundError:
    st.error("File games.csv tidak ditemukan! Pastikan sudah di-upload ke GitHub.")
    st.stop()

# Setup Model AI
@st.cache_resource
def train_model(df):
    cols = ["platform", "genre", "metacritic_score", "global_sales_million"]
    df_clean = df[cols].dropna()
    df_enc = pd.get_dummies(df_clean, columns=["genre", "platform"])

    X = df_enc.drop("global_sales_million", axis=1)
    y = df_enc["global_sales_million"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = xgb.XGBRegressor(objective="reg:squarederror", n_estimators=100, learning_rate=0.1, random_state=42)
    model.fit(X_train, y_train)

    # Hitung data pembanding
    y_pred = model.predict(X_test)
    df_validation = pd.DataFrame({
        'Penjualan Asli (Actual)': y_test.values,
        'Prediksi AI (Predicted)': np.round(y_pred, 2)
    })

    return model, X.columns, df_validation

model, features, df_val = train_model(df_games)

st.sidebar.header("⚙️ Parameter Simulasi")
user_genre = st.sidebar.selectbox("Kategori Genre", df_games["genre"].dropna().unique())
user_platform = st.sidebar.selectbox("Platform Rilis", df_games["platform"].dropna().unique())
user_score = st.sidebar.slider("Target Metacritic Score", min_value=10, max_value=100, value=80)

if st.sidebar.button("🚀 Kalkulasi Potensi Penjualan", use_container_width=True):
    input_df = pd.DataFrame(0, index=[0], columns=features)
    input_df["metacritic_score"] = user_score

    g_col, p_col = f"genre_{user_genre}", f"platform_{user_platform}"
    if g_col in input_df.columns: input_df[g_col] = 1
    if p_col in input_df.columns: input_df[p_col] = 1

    prediksi = model.predict(input_df)[0]

    st.sidebar.success("Kalkulasi Selesai!")
    st.sidebar.metric(label="Estimasi Penjualan Global", value=f"{prediksi:.2f} Juta Kopi")

tab1, tab2 = st.tabs(["📈 Market Insights", "🤖 Model Validation"])

with tab1:
    st.subheader("Top 10 Genre dengan Pendapatan Tertinggi")

    # Kalkulasi Agregasi Genre
    top_genres = df_games.groupby('genre')['global_sales_million'].sum().reset_index()
    top_genres = top_genres.rename(columns={'global_sales_million': 'total_sales_m'})
    top_genres = top_genres.sort_values(by="total_sales_m", ascending=False).head(10)

    # Visualisasi Plotly
    fig = px.bar(
        top_genres,
        x="genre",
        y="total_sales_m",
        color="total_sales_m",
        color_continuous_scale="Viridis",
        labels={"genre": "Genre Game", "total_sales_m": "Total Penjualan (Juta Kopi)"}
    )
    st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.subheader("Data Pembanding (Testing Data 20%)")
    st.write("Tabel ini membuktikan kepada penguji bahwa AI mampu memprediksi pola penjualan mendekati angka aslinya, bukan sekadar menghafal data.")
    st.dataframe(df_val.head(50), use_container_width=True)